// include "/media/sf_ubuntu_vm_shared/malware_yara/Adwind.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/AgentTesla.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Akira.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Amadey.yar"
// include "/media/sf_ubuntu_vm_shared/malware_yara/andr_spynote.yara"
include "/media/sf_ubuntu_vm_shared/malware_yara/apt_cobaltstrike.yar"
// include "/media/sf_ubuntu_vm_shared/malware_yara/APT_Dropper_Raw64_TEARDROP_1 (1).yar"
// include "/media/sf_ubuntu_vm_shared/malware_yara/APT_Dropper_Raw64_TEARDROP_1.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/apt_nanocore_rat.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/apt_netwire_rat.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/apt_quasar_rat.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/ATM.Malware.Ploutus-I.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/avemaria_warzone.yara"
include "/media/sf_ubuntu_vm_shared/malware_yara/Azorult.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/BadRabbit.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/blackmoon_banker.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Cerber.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/crime_goldeneye.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/crime_mirai.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/crime_nopetya_jun17.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/crime_socgholish.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/crime_wannacry.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Dridex.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/elf.bashlite_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/EMAIL_Cryptowall.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Emotet.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Formbook.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/gen_mimikatz.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/Lockbit2.Stealbit.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/mal_netsha.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/MALW_Pony.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/MALW_redline.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/MALW_Tinba.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/MALW_TrickBot.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/metasploit.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/pua_xmrig_monero_miner.yar"
// include "/media/sf_ubuntu_vm_shared/malware_yara/Qakbot.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RaccoonV2.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/ramnit.yar"
// include "/media/sf_ubuntu_vm_shared/malware_yara/RANSOM_MS17-010_Wannacrypt.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RANSOM_PetrWrap.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RANSOM_Satana.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RANSOM_Sodinokibi.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RAT_CyberGate.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RAT_Njrat.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RAT_Ratdecoders.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/RisePro.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/sality.yara"
include "/media/sf_ubuntu_vm_shared/malware_yara/SmokeLoader.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/SnakeKeylogger.yara"
// include "/media/sf_ubuntu_vm_shared/malware_yara/Stealc Malware YARA Rule.txt"
include "/media/sf_ubuntu_vm_shared/malware_yara/telsacrypt yara rule.txt"
include "/media/sf_ubuntu_vm_shared/malware_yara/Troj-gootloader.yara"
include "/media/sf_ubuntu_vm_shared/malware_yara/Vidar.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.ardamax_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.cloudeye_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.cloudeye_w0.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.darkcomet_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.gandcrab_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.gcleaner_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.gcleaner_w0.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.ghost_rat_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.glupteba_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.gozi_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.hawkeye_keylogger_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.hawkeye_keylogger_w0.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.icedid_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.isfb_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.kpot_stealer_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.kpot_stealer_w0.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.lockbit_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.locky_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.lokipws_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.lumma_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.lumma_w0.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.lumma_w1.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.masslogger_w0.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win.matsnu_auto.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win_mal_XWorm.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win_mal_Zloader.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/win_privateloader.yara"
include "/media/sf_ubuntu_vm_shared/malware_yara/Windows_Trojan_Latrodectus.yar"
include "/media/sf_ubuntu_vm_shared/malware_yara/XLoader_MacOS.yar"
//include "/media/sf_ubuntu_vm_shared/malware_yara/newindex.yar"
